export const rowdata = [
  {
    key: "1",
    image: "image1",
    title: "Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "Jane Cooper",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: true,
    date: "24 nov 2022",
  },
  {
    key: "2",
    image: "image1",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: false,
    date: "24 nov 2022",
  },
  {
    key: "3",
    image: "image1",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: false,
    date: "24 nov 2022",
  },
  {
    key: "4",
    image: "image1",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: true,
    date: "24 nov 2022",
  },
  {
    key: "5",
    image: "image1",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: false,
    date: "24 nov 2022",
  },
  {
    key: "6",
    image: "image1",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: true,
    date: "24 nov 2022",
  },
  {
    key: "7",
    image: "image1",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: false,
    date: "24 nov 2022",
  },
  {
    key: "8",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZof_FZRtmnOMMWtNarqAN0CPc0v0dwQ8DCw&usqp=CAU",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: true,
    date: "24 nov 2022",
  },
  {
    key: "9",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZof_FZRtmnOMMWtNarqAN0CPc0v0dwQ8DCw&usqp=CAU",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: true,
    date: "24 nov 2022",
  },
  {
    key: "10",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZof_FZRtmnOMMWtNarqAN0CPc0v0dwQ8DCw&usqp=CAU",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: false,
    date: "24 nov 2022",
  },
  {
    key: "11",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZof_FZRtmnOMMWtNarqAN0CPc0v0dwQ8DCw&usqp=CAU",
    title:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, provident! Laborum, culpa voluptate veritatis minus facere illum maxime magni a commodi quia hic id assumenda tempore cupiditate voluptates nostrum similique?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "New Mexico",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: true,
    date: "24 nov 2022",
  },
  {
    key: "12",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZof_FZRtmnOMMWtNarqAN0CPc0v0dwQ8DCw&usqp=CAU",
    title: " Future of Javascript In 2022: What To Expect Next?",
    email: "Janecooper@gamil.com",
    address: "4140 Parker Rd. Allentown, New Mexico 31134",
    city: "Rajkot",
    organizername: "savan",
    description:
      "There are countless programming languages used in the IT industry. Although most programming languages share the same syntax, each has unique characteristics. ",
    phone: +911234567890,
    totallike: 20,
    status: false,
    date: "24 nov 2022",
  },
];
